name: IE11 - DataPreload

on:
  push:
    branches: [ master ]    
    paths:
      - 'ie11-datapreload/**'
      - '.github/workflows/ie11-datapreload.yml' 
  pull_request:
    branches: [ master ]
    paths: 
      - 'ie11-datapreload/**'
      - '.github/workflows/ie11-datapreload.yml'

env:
  clientId: f6ac0ba1-bc7b-48cc-8d18-adf7efac86bb
  tenant: aitabeb2c.onmicrosoft.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy TrustFrameworkBase
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "./ie11-datapreload/TrustFrameworkBase.xml"
        policy: B2C_1A_IE11_Data-Preload_TrustFrameworkBase
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.clientSecret }}
    
    - name: Deploy TrustFrameworkExtensions
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "./ie11-datapreload/TrustFrameworkExtensions.xml"
        policy: B2C_1A_IE11_Data-Preload_TrustFrameworkExtensions
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.clientSecret }}
    
    - name: Deploy SignUpOrSignin
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "./ie11-datapreload/SignUpOrSignin.xml"
        policy: B2C_1A_IE11_Data-Preload_SignUp_Signin
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.clientSecret }}
    
    - name: Deploy ProfileEdit
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "./ie11-datapreload/ProfileEdit.xml"
        policy: B2C_1A_IE11_Data-Preload_ProfileEdit
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.clientSecret }}
    
    - name: Deploy PasswordReset
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "./ie11-datapreload/PasswordReset.xml"
        policy: B2C_1A_IE11_Data-Preload_PasswordReset
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.clientSecret }}
        
    - name: Deploy UI
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        source_dir: azure-ad-b2c/ie11-datapreload/UI
        container_name: ie11-datapreload
        connection_string: ${{ secrets.aitabeb2cui_ConnectionString }}
