name: IE11 - DataPreload

on:
  push:
    branches: [ master ]    
    paths: ie11-datapreload/**
  pull_request:
    branches: [ master ]
    paths: ie11-datapreload/**

env:
  clientId: 591d586f-3f7e-4345-85d7-60fcf5a5ab9e
  tenant: aitabeb2c.onmicrosoft.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Azure AD B2C TrustFramework Policy
      uses: azure-ad-b2c/deploy-trustframework-policy@v1
      with:
        file: "./ie11-datapreload/TrustFrameworkBase.xml"
        policy: B2C_1A_IE11_Data-Preload_TrustFrameworkBase
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.clientSecret }}
